/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IaCheckbox } from "./components/switch/switch";
export namespace Components {
    interface AppRoot {
    }
    interface IaAlert {
        /**
          * 是否显示关闭按钮
         */
        "closeable": boolean;
        /**
          * 提示文字内容
         */
        "content": string;
        /**
          * 当前提示的描述
         */
        "description": string;
        /**
          * 提示类型
         */
        "type": 'success' | 'error' | 'warning' | 'info';
    }
    interface IaButton {
        /**
          * 是否被禁用
         */
        "disabled": boolean;
        /**
          * 是否正在加载中
         */
        "loading": boolean;
        /**
          * 是否设置圆角
         */
        "round": boolean;
        /**
          * 按钮类型
         */
        "type": 'primary' | 'success' | 'info' | 'warning' | 'error' | 'text';
    }
    interface IaPlayground {
    }
    interface IaSwitch {
        /**
          * 是否开启
         */
        "checked": boolean;
        /**
          * 是否被禁用
         */
        "disabled": boolean;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLIaAlertElement extends Components.IaAlert, HTMLStencilElement {
    }
    var HTMLIaAlertElement: {
        prototype: HTMLIaAlertElement;
        new (): HTMLIaAlertElement;
    };
    interface HTMLIaButtonElement extends Components.IaButton, HTMLStencilElement {
    }
    var HTMLIaButtonElement: {
        prototype: HTMLIaButtonElement;
        new (): HTMLIaButtonElement;
    };
    interface HTMLIaPlaygroundElement extends Components.IaPlayground, HTMLStencilElement {
    }
    var HTMLIaPlaygroundElement: {
        prototype: HTMLIaPlaygroundElement;
        new (): HTMLIaPlaygroundElement;
    };
    interface HTMLIaSwitchElement extends Components.IaSwitch, HTMLStencilElement {
    }
    var HTMLIaSwitchElement: {
        prototype: HTMLIaSwitchElement;
        new (): HTMLIaSwitchElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "ia-alert": HTMLIaAlertElement;
        "ia-button": HTMLIaButtonElement;
        "ia-playground": HTMLIaPlaygroundElement;
        "ia-switch": HTMLIaSwitchElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface IaAlert {
        /**
          * 是否显示关闭按钮
         */
        "closeable"?: boolean;
        /**
          * 提示文字内容
         */
        "content"?: string;
        /**
          * 当前提示的描述
         */
        "description"?: string;
        /**
          * 提示类型
         */
        "type"?: 'success' | 'error' | 'warning' | 'info';
    }
    interface IaButton {
        /**
          * 是否被禁用
         */
        "disabled"?: boolean;
        /**
          * 是否正在加载中
         */
        "loading"?: boolean;
        /**
          * 是否设置圆角
         */
        "round"?: boolean;
        /**
          * 按钮类型
         */
        "type"?: 'primary' | 'success' | 'info' | 'warning' | 'error' | 'text';
    }
    interface IaPlayground {
    }
    interface IaSwitch {
        /**
          * 是否开启
         */
        "checked"?: boolean;
        /**
          * 是否被禁用
         */
        "disabled"?: boolean;
        /**
          * 改变事件
         */
        "onIaChange"?: (event: CustomEvent<IaCheckbox>) => void;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "ia-alert": IaAlert;
        "ia-button": IaButton;
        "ia-playground": IaPlayground;
        "ia-switch": IaSwitch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "ia-alert": LocalJSX.IaAlert & JSXBase.HTMLAttributes<HTMLIaAlertElement>;
            "ia-button": LocalJSX.IaButton & JSXBase.HTMLAttributes<HTMLIaButtonElement>;
            "ia-playground": LocalJSX.IaPlayground & JSXBase.HTMLAttributes<HTMLIaPlaygroundElement>;
            "ia-switch": LocalJSX.IaSwitch & JSXBase.HTMLAttributes<HTMLIaSwitchElement>;
        }
    }
}
